### ISSUE TITLE
How to train and test my data? And How to create my config file? Thanks

### ISSUE THREAD

**Issue by HK017** [google-research/l2p#5]
It's nice to have such a great work, but I'm at a loss to train my own data and ask for your help

**Comment by iamwangyabin** [comment]
You need to store your data using tensorflow_dataset(tfds) and build it. Then you need to add your data in "input_pipeline.py". There is a sample code of Imagenet for your reference. And you have to modify "class_stats.py".
Good Luck!

**Comment by HK017** [comment]
Thank you for your reply. I built my own data set according to your reply, but there was an error that I could not find the `tfreord` file during the training phase? Do I need to manually generate `.tfreord` data to create my own dataset?
The error message is as follows:
```
I0507 14:02:24.524774 140079258777408 utils_vit.py:150] load_pretrained: drop-head variant
I0507 14:02:24.584433 140079258777408 train_continual.py:595] global_batch_size=16, num_train_steps=4045, steps_per_epoch=809, eval_every_steps=809
/home/ai/software/l2p/venv/lib/python3.8/site-packages/jax/lib/xla_bridge.py:368: UserWarning: jax.host_count has been renamed to jax.process_count. This alias will eventually be removed; please update your code.
  warnings.warn(
/home/ai/software/l2p/venv/lib/python3.8/site-packages/jax/lib/xla_bridge.py:355: UserWarning: jax.host_id has been renamed to jax.process_index. This alias will eventually be removed; please update your code.
  warnings.warn(
I0507 14:02:24.727394 140062708610816 logging_writer.py:57] Hyperparameters: {'checkpoint_every_steps': 5000, 'continual': class_order:
- 68
- 56
- 78
- 8
- 23
- 84
- 90
- 65
- 74
- 76
- 40
- 89
- 3
- 92
- 55
- 9
- 26
- 80
- 43
- 38
- 58
- 70
- 77
- 1
- 85
- 19
- 17
- 50
- 28
- 53
- 13
- 81
- 45
- 82
- 6
- 59
- 83
- 16
- 15
- 44
- 91
- 41
- 72
- 60
- 79
- 52
- 20
- 10
- 31
- 54
- 37
- 95
- 14
- 71
- 96
- 98
- 97
- 2
- 64
- 66
- 42
- 22
- 35
- 86
- 24
- 34
- 87
- 21
- 99
- 0
- 88
- 27
- 18
- 94
- 11
- 12
- 47
- 25
- 30
- 46
- 62
- 69
- 36
- 61
- 7
- 63
- 75
- 5
- 32
- 4
- 51
- 48
- 73
- 93
- 39
- 67
- 29
- 49
- 57
- 33
eval_task_inc: false
num_classes_per_task: 10
num_tasks: 10
num_train_steps_per_task: -1
rand_seed: 1993
train_mask: true
, 'dataset': 'imagenet100', 'eval_every_steps': -1, 'eval_last_only': False, 'eval_pad_last_batch': False, 'freeze_bn_stats': False, 'freeze_part': ['encoder', 'embedding', 'cls'], 'gaussian_schedule': False, 'grad_clip_max_norm': 1.0, 'init_checkpoint': 'models/ViT-B_16.npz', 'input_size': 224, 'learning_rate': 0.03, 'learning_rate_schedule': 'constant', 'log_loss_every_steps': 3, 'model_config': classifier: prompt
hidden_size: 768
num_tasks: 10
patches:
  size: !!python/tuple
  - 16
  - 16
prompt_params:
  prompt_pool:
    batchwise_prompt: true
    embedding_key: cls
    initializer: uniform
    length: 5
    pool_size: 10
    prompt_key: true
    prompt_key_init: uniform
    top_k: 5
    use_prompt_mask: false
representation_size: null
temperature: 1
transformer:
  attention_dropout_rate: 0.0
  dropout_rate: 0.0
  mlp_dim: 3072
  num_heads: 12
  num_layers: 12
use_cls_token: true
, 'model_name': 'ViT-B_16', 'norm_01': True, 'norm_pre_logits': False, 'num_epochs': 5, 'num_eval_steps': -1, 'num_total_class': 100, 'optim': 'adam', 'per_device_batch_size': 16, 'predefined_key_path': '', 'prompt_histogram': True, 'prompt_pool': True, 'prompt_pool_param': batchwise_prompt: true
embedding_key: cls
initializer: uniform
length: 5
pool_size: 10
prompt_key: true
prompt_key_init: uniform
top_k: 5
use_prompt_mask: false
, 'pull_constraint': True, 'pull_constraint_coeff': 0.1, 'reinit_optimizer': True, 'resize_size': 256, 'reverse_task': False, 'save_last_ckpt_only': True, 'seed': 1993, 'sgd_momentum': 0.9, 'shuffle_buffer_size': 10000, 'subsample_rate': -1, 'task_specific_cls_token': False, 'temperature': 1, 'trial': 0, 'use_cls_token': True, 'use_prompt': True, 'vit_classifier': 'prompt', 'warmup_epochs': 0, 'weight_decay': 0, 'weight_norm': False}
I0507 14:02:24.733685 140079258777408 train_continual.py:650] Starting training loop at step 1.
Traceback (most recent call last):
  File "/home/ai/software/l2p/main.py", line 64, in <module>
    app.run(main)
  File "/home/ai/software/l2p/venv/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/ai/software/l2p/venv/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/ai/software/l2p/main.py", line 58, in main
    train_continual.train_and_evaluate(FLAGS.my_config, FLAGS.workdir)
  File "/home/ai/software/l2p/train_continual.py", line 936, in train_and_evaluate
    state, rng = train_and_evaluate_per_task(task_id, config, workdir, **kwargs)
  File "/home/ai/software/l2p/train_continual.py", line 707, in train_and_evaluate_per_task
    batch = jax.tree_map(np.asarray, next(train_iter))
  File "/home/ai/software/l2p/venv/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 836, in __next__
    return self._next_internal()
  File "/home/ai/software/l2p/venv/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 819, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/home/ai/software/l2p/venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2923, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ai/software/l2p/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: /home/ai/tensorflow_datasets/my_dataset/1.0.0/my_dataset-train.tfrecord-00031-of-00100; No such file or directory [Op:IteratorGetNext]
```

Looking forward to reply. Thank you!

**Comment by HK017** [comment]
@iamwangyabin I looked at the code, it was code error of `next(train_iter)`.

**Comment by KingSpencer** [comment]
Thanks for these meaningful discussion!
